### PR TITLE
test: add playwright package and tests to run on GH actions

### PR DESCRIPTION
**Pull request by KrupaPammi**

### CODE REVIEW

**Comment by KrupaPammi** [comment]
Hi @AndyEPhipps, this PR is ready for review. 

I see some problems with lint; I'm not sure how to fix them. Would you be able to look into it please?

Screenshot 2023-11-16 at 09 01 19

**Review by AndyEPhipps — APPROVED** [review]
There's a lot going on here, but I trust your work!

Will need to look into those GitHubAction Lint errors in another PR if we can

**Comment by AndyEPhipps** [comment]
Have fixed those; it seems like Actions is using a different Linting ruleset to what's used locally; will suss out how to align these in the near future.

**Comment by KrupaPammi** [comment]
> Have fixed those; it seems like Actions is using a different Linting ruleset to what's used locally; will suss out how to align these in the near future.

Thanks Andy

**Pull request merged**
