### PR TITLE
Spacing helper

### LINKED ISSUE #60: Add spacing helper
Remove "magic numbers" ie. `margin: 11px 7px;` we should have some like "`margin: sm md;`"

### PR DESCRIPTION
**Pull request by LouiaR**
Type: patch

Fixes #60

### CODE REVIEW

**Comment by gusliedke** [comment]
@LouiaR can you add instructions on `docs/utils`?

**Comment by LouiaR** [comment]
> @LouiaR can you add instructions on `docs/utils`?

Sure

**Comment by gusliedke** [comment]
👍 🚢

**Pull request merged**
