### PR TITLE
feat: add in additional copy fields to widget

### PR DESCRIPTION
**Pull request by AndyEPhipps**
#### What is it doing?
Adds new optional props for some additional copy for either giving type:

#### Why is this required?
Evening Standard kicking off about having to have some extra messaging specifically on the Monthly selection on the Winter Appeal page

#### link to Jira ticket:
https://comicrelief.atlassian.net/browse/ENG-2920

### Quick Checklist:
- [x] My PR title follows the Conventional Commit spec.

- [x] I have filled out the PR description as per the template above.

- [x] I have added tests to cover new or changed behaviour.

- [x] I have updated any relevant documentation.

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
Single only: https://deploy-preview-606--cr-component-library.netlify.app/#!/Donate/31

Monthly only: https://deploy-preview-606--cr-component-library.netlify.app/#!/Donate/31

Both: https://deploy-preview-606--cr-component-library.netlify.app/#!/Donate/27

**Comment by KrupaPammi** [comment]
@AndyEPhipps for `monthly only` one, I don't see any additional copy fields like the single one https://deploy-preview-606--cr-component-library.netlify.app/#!/Donate/31

**Comment by AndyEPhipps** [comment]
> @AndyEPhipps for `monthly only` one, I don't see any additional copy fields like the single one https://deploy-preview-606--cr-component-library.netlify.app/#!/Donate/31

Sorry, copy-paste error; updated

**Comment by KrupaPammi** [comment]
Looks good @AndyEPhipps

**Review by KrupaPammi — APPROVED** [review]

**Pull request merged**
