### PR TITLE
feat: Updates to donate widget - part 2

### PR DESCRIPTION
**Pull request by michael-odonovan**
#### What is it doing?
Makes more substantial changes to the Donate widget front end and Contentful CMS fields.

#### Why is this required?
requested by Fundraising.

#### link to Jira ticket:
[[Add a link to the Jira ticket.](https://comicrelief.atlassian.net/browse/ENG-1796)](https://comicrelief.atlassian.net/browse/ENG-1810)

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
Yo, remember this is gonna be one PR for everything else; not just this _one_ change

**Comment by AndyEPhipps** [comment]
Let's add a version to the CL that has no summary passed, and then fix the inevitable alignment issue it brings up, like I mentioned this morning

**Comment by michael-odonovan** [comment]
man I thought I had this marked as draft...
Sure I'll slack you

**Comment by AndyEPhipps** [comment]
Okay, getting myself confused. All the new CL work also needs to be a single PR. We can't release bits and pieces of this work really, so dividing it up into different releases will make this a dangerous possibility (for instance, if there's some urgent CL fix that's needed to go live in the meantime)

**Comment by AndyEPhipps** [comment]
> man I thought I had this marked as draft... Sure I'll slack you

It still pings us even when it's a draft alas

**Comment by AndyEPhipps** [comment]
All new work now in https://github.com/comicrelief/component-library/pull/500

**Pull request closed without merging**
