### PR TITLE
feat: Add Label component

### PR DESCRIPTION
**Pull request by tomisaacmarshall**
To reduce repeated code across form controls and ensure they have consistent label styling

### CODE REVIEW

**Comment by gusliedke** [comment]
Maybe call it **Label** instead?

**Comment by tomisaacmarshall** [comment]
> Maybe call it **Label** instead?

I nearly did but as it also displays the error message under the field, thought it wasn't quite right

**Comment by tomisaacmarshall** [comment]
> > Maybe call it **Label** instead?
> 
> I nearly did but as it also displays the error message under the field, thought it wasn't quite right

Perhaps I should change it so the error message goes back into the input/select/textarea component, and this is just the label?

**Comment by gusliedke** [comment]
> > > Maybe call it **Label** instead?
> > 
> > 
> > I nearly did but as it also displays the error message under the field, thought it wasn't quite right
> 
> Perhaps I should change it so the error message goes back into the input/select/textarea component, and this is just the label?

Yeah I think just Label would be better .. and Error msg stay flexible where it displays

**Comment by tomisaacmarshall** [comment]
> > > > Maybe call it **Label** instead?
> > > 
> > > 
> > > I nearly did but as it also displays the error message under the field, thought it wasn't quite right
> > 
> > 
> > Perhaps I should change it so the error message goes back into the input/select/textarea component, and this is just the label?
> 
> Yeah I think just Label would be better .. and Error msg stay flexible where it displays

@gusliedke agreed. Will update

**Review by gusliedke — APPROVED** [review]

**Pull request merged**
