### PR TITLE
Fix: Issue with Input component duplicating props & adding event handlers twice

### LINKED ISSUE #290: Fix issue with Input component duplicating props (event handlers in particular)
The `<Input>` component was passing additional props captured by `...rest` to two of its child components, Label and InputField (with a few exceptions which were prevented being added to Label)

This duplication was a particular problem for event handlers - e.g. any onChange or onClick prop provided to Input would fire twice.

Classes inserted by styled components were also being added to both children, rather than just the outer element.

### PR DESCRIPTION
**Pull request by tomisaacmarshall**
Fixes #290 

Type: patch

## Changes proposed in this PR

- Alters the Input component so that props captured by `...rest` (including event handlers) are only added to the InputField element
- Adds className prop to Input and passes this to the outer element, Label, only (previously className was being added to both elements)

### CODE REVIEW

**Comment by adamclark-dev** [comment]
@AndyEPhipps @LouiaR @gusliedke could you review

**Comment by AndyEPhipps** [comment]
Makes sense to me, @tomisaacmarshall! 

In order to update the snapshot (so your Circle CI build will pass), you need to run `yarn test -u` locally.

Although it's a pretty minor change, we'd normally pull in this PR version of Component Library into an PR env of the context it's being used in (CR.com in this instance) so make sure there's been unexpected side effects _**in-situ**_

**Comment by AndyEPhipps** [comment]
Also (although it's not documented), but you wanna use a fix:/feat:/BREAKING CHANGE: prefix to one of the commit messages.

It's used by Semantic Versioning to determine which version to bump the package to with this PR.

It's documented here: https://github.com/comicrelief/pattern-lab, will update the docs here shortly.

**Comment by gusliedke** [comment]
Hi Tom, feel free to refactor / clean up Input component. We use it only in Search, Donate widget, EmailSignUp and Membership components. If you change it just update the snap tests, create a PR as per Andy's instructions and we can ask Krupa to test those specifics affected components in CR app.

**Comment by tomisaacmarshall** [comment]
@gusliedke @AndyEPhipps Thanks for comments!

I've been a bit bolder with the changes now, as well as running the snapshot update and adding the commit prefix

Don't fully understand the PR bit though @AndyEPhipps ?

**Pull request merged**
