### PR TITLE
feat: add data-attribute to CardDS & SingleMsgDS for GA reasons

### PR DESCRIPTION
**Pull request by AndyEPhipps**
#### What is it doing?
Just makes the CTA copy available to the GA when the user clicks on the img link, rather than the button; that way, Hiral and co. can better track the journey in relation to the content.

#### Why is this required?
Better GA insight

#### link to Jira ticket:
No ticket, just had a convo and it came up

### Quick Checklist:
- [x] My PR title follows the Conventional Commit spec.

- [x] I have filled out the PR description as per the template above.

- [x] I have added tests to cover new or changed behaviour.

- [x] I have updated any relevant documentation.

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
@michael-odonovan @pauldolden: if you can give this a look please, I'd appreciate it, not least because it needs to be in place in CRcom before the forthcoming GA update work is started.

**Comment by pauldolden** [comment]
> @michael-odonovan @pauldolden: if you can give this a look please, I'd appreciate it, not least because it needs to be in place in CRcom before the forthcoming GA update work is started.

Will look at this, this morning.

**Review by pauldolden — APPROVED** [review]
All looks good to me :)

**Comment by AndyEPhipps** [comment]
Thanks Paul :)

**Pull request merged**
