### PR TITLE
feat: add chevron svg

### PR DESCRIPTION
**Pull request by michael-odonovan**
#### What is it doing?
Add cheveron-down icon to the navbar links that have a secondary dropdown menu.

#### Why is this required?
Improve UI / Fundraising request.

#### link to Jira ticket:
https://comicrelief.atlassian.net/browse/ENG-1740

### CODE REVIEW

**Comment by KrupaPammi** [comment]
Hi @michael-odonovan can I the url to test this please?

**Comment by michael-odonovan** [comment]
Hey Krupa, I'm a bit confused => perhaps you don't usually test things that are only changes to the CL?

**Comment by KrupaPammi** [comment]
Yeah it's mostly after these changes are implemented on Comicrelief-Contentful PR I test.

**Comment by michael-odonovan** [comment]
Ok apologies Krupa, I will get Paul to ok this, and then I will set them up on CR.com

**Review by pauldolden — APPROVED** [review]
Looks good to me.

**Pull request merged**
