### PR TITLE
feat: Make Confetti Separate Component

### PR DESCRIPTION
**Pull request by michael-odonovan**
### PR description
Make Confetti Separate Component

#### Why is this required?
We are using this Confetti idea in multiple places / DRY

#### Jira Ticket
https://comicrelief.atlassian.net/browse/ENG-1959

### CODE REVIEW

**Comment by michael-odonovan** [comment]
This confetti runs as soon as you run the local server, so is kind of annoying / not the best way of viewing the actual confetti.

**Review by AndyEPhipps — CHANGES_REQUESTED** [review]
Looking good, but could we remove it from the ESU component, and add this version in?

**Comment by michael-odonovan** [comment]
Yeh we have a ticket for that, which I am gonna handle after this sprint. One step ahead of you...

**Comment by michael-odonovan** [comment]
I will do the other FSU usage at the same time as well

**Comment by AndyEPhipps** [comment]
Any reason why we can't just do it now as part of this work?

**Comment by AndyEPhipps** [comment]
Eh, screw it, I guess we can do it later.

Have you been able to test within your CRcom build locally?

**Review by AndyEPhipps — APPROVED** [review]
Nice oooone 👍

**Pull request merged**
