### PR TITLE
feat: Donate Widget updates: button copy, moneybuy text position

### PR DESCRIPTION
**Pull request by michael-odonovan**
#### What is it doing?
Makes the two simple "QUICK WINS" improvements from the from Donate widget sprint.

#### Why is this required?
Requested by fundraising.

#### link to Jira ticket:
https://comicrelief.atlassian.net/browse/ENG-1800
https://comicrelief.atlassian.net/browse/ENG-1798

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
Yo @michael-odonovan, do you wanna do this work one PR per issue/ticket? Might make it a bit easier to manage

**Comment by michael-odonovan** [comment]
Hey Andy => yeh sure, makes sense. So go back to master, make branch name that references the Jira ticket, create PR, get approved/merged in. Then repeat?

**Comment by AndyEPhipps** [comment]
That's the fella!

**Comment by AndyEPhipps** [comment]
Make sure we get Krupa involved for each of them too, no matter how small - it'll catch any weird cross-browser F/E bugs that might creep in, but also keeps her updated as to the changes in general, as there could/should be test updates made that reflect some of the changes.

**Comment by michael-odonovan** [comment]
Is it possible to have a update-widget PR, and then have individual ticket PRs off that?

**Comment by AndyEPhipps** [comment]
It _is_ possible though, yes

**Review by AndyEPhipps — APPROVED** [review]

**Pull request merged**
