### PR TITLE
feat: add 'xsmall' screen size to media helper

### PR DESCRIPTION
**Pull request by tomisaacmarshall**
This ok?

### CODE REVIEW

**Comment by gusliedke** [comment]
What's the new breakpoint for?

**Comment by tomisaacmarshall** [comment]
> What's the new breakpoint for?

Just thought it'd be useful to be able to target v small screens?

**Comment by gusliedke** [comment]
> > What's the new breakpoint for?
> 
> Just thought it'd be useful to be able to target v small screens?



> > What's the new breakpoint for?
> 
> Just thought it'd be useful to be able to target v small screens?

Only if we need to make the design to look different when on a small mobile screen vs large mobile screen. I don't think we want that. The idea is mobile first and the next breakpoint (design change) is just before tablet.

**Comment by tomisaacmarshall** [comment]
> > > What's the new breakpoint for?
> > 
> > 
> > Just thought it'd be useful to be able to target v small screens?
> 
> > > What's the new breakpoint for?
> > 
> > 
> > Just thought it'd be useful to be able to target v small screens?
> 
> Only if we need to make the design to look different when on a small mobile screen vs large mobile screen. I don't think we want that. The idea is mobile first and the next breakpoint (design change) is just before tablet.

Ok!

**Pull request closed without merging**
